### ISSUE TITLE
Suggestion - assign someone to submit the VAT return

### ISSUE THREAD

**Issue by chrisroos** [freerange/harmonia-old#1]
It feels to me like this would be a good fit for harmonia.  Any thoughts?

**Comment by lazyatom** [comment]
It would get the appropriate dates by querying FreeAgent? I suppose we know them all relatively far in advance, and could just provide some kind of yaml list of dates...?

**Comment by chrisroos** [comment]
I believe the dates are fairly static so we could just provide a fixed list in some way.

**Comment by floehopper** [comment]
It may be overkill, but FreeAgent provides an iCal feed - see the Tax Timeline here [1].

[1] https://freerange.freeagentcentral.com/settings/api

**Comment by lazyatom** [comment]
Done, via parsing an iCal feed.
