### ISSUE TITLE
Corrupted assignments.yml

### ISSUE THREAD

**Issue by lazyatom** [freerange/harmonia-old#10]
Earlier today the file looked like this when trying to perform assignments:

```
--- {}
eknotes: Jase
:fire_logbook: Chris
```

My theory is that all of the unassignments running simultaneously (at 11:59) caused multiple processes to write to the file.

**Comment by floehopper** [comment]
I've pushed an attempted fix for this into a branch - 2c17a71e95675ba7b1e775093ed7846a23374284. Let me know what you think and I can try to deploy it if you think it's worth a shot. Cheers, JM.

**Comment by lazyatom** [comment]
Looks good to me James. Have you checked the generated crontab from whenever, locally? (i.e. confirmed that the `*:tasks` expands as you hope).

**Comment by floehopper** [comment]
Indeed. I generated the crontab locally and ran a couple of the commands from within it. I think I'll deploy it now.

**Comment by floehopper** [comment]
I think we can say this is now fixed.
