### ISSUE TITLE
Assign the annual return

### ISSUE THREAD

**Issue by lazyatom** [freerange/harmonia-old#11]
Next due on the 29th of January. This should be easy to implement in a similar way to VAT returns.

**Comment by jasoncale** [comment]
I've added task for this bad boy, should be good to go although some refactoring might be nice.

**Comment by lazyatom** [comment]
Looks good to me Jase - I've added it to the schedule and deployed (cfdbb004fee42169bd203e173e7776a6591bfd4f)
