### ISSUE TITLE
Assign the corporation tax payment

### ISSUE THREAD

**Issue by lazyatom** [freerange/harmonia-old#12]
Next due on the 31st of January. This should be easy to implement in a similar way to VAT returns.

**Comment by jasoncale** [comment]
I've just popped a couple of commits in for both the submission, and payment.

**Comment by floehopper** [comment]
It looks to me as if @jasoncale has fixed this in dffd1fd2e13ba8aa8a205ef4059ba62f8683a213, 1f260b7d4b347b59360cb4d77de70098db60aec6 & 3fcaf1db3ce21f5a9a89b6b2894d3c68e20692b6. Can we now close this issue? Or is something missing?

**Comment by lazyatom** [comment]
I think we're done.
