### ISSUE TITLE
Split PAYE out of the payroll task?

### ISSUE THREAD

**Issue by lazyatom** [freerange/harmonia-old#14]
Since this needs to happen only every quarter, it could quite easily be separated into its own task. I guess the question comes down to whether or not we prefer more smaller tasks, or fewer more-comprehensive tasks?

**Comment by floehopper** [comment]
Splitting it out gets my vote. +1?

**Comment by chrisroos** [comment]
I've implemented this is 11f1ce131734dda3be6dfa5b3ac733b681ffaa13.  I'd love someone to give that commit the once over to ensure that I haven't done anything crazy stoopid.

**Comment by lazyatom** [comment]
Looks good to me Chris. This'll all get easier with harmonia-next.
