### ISSUE TITLE
Overdue invoices are not listed

### ISSUE THREAD

**Issue by lazyatom** [freerange/harmonia-old#4]
See the bodge added in b0ea0d608cebe055e51ef2a5577e23cc2c5b3427.

**Comment by floehopper** [comment]
I believe I have fixed this in 924b39a9a8ba57afb33d308a8551b4f3f753dc5e. I reproduced the problem on the server by tweaking the query to include "open" invoices. I then deployed this fix and could no longer reproduce the problem using the same tweak. The tweak has now been removed from the server. Fingers crossed it will work next week.
