### ISSUE TITLE
Suggestion: Add outstanding bill payments to the invoice responsibilities

### ISSUE THREAD

**Issue by chrisroos** [freerange/harmonia-old#6]
The idea is that we add a list of bills that need to be paid within the next week (as defined in FreeAgent) to the invoice email currently sent on Mondays.

**Comment by lazyatom** [comment]
Sounds good to me. I had to disable the outstanding invoice stuff, but once that is fixed this could also be added.

**Comment by floehopper** [comment]
This is a good idea. On a related note, I subscribe to the tax & invoice iCal timelines from FA [1]. It would be nice if they provided a bill timeline too. I'll post something on their GS.

[1] https://freerange.freeagentcentral.com/settings/api

**Comment by floehopper** [comment]
Hmm. According to this [1], they already show up in one of the existing feeds.

[1] http://community.freeagent.com/freeagent/topics/itd_be_great_if_bills_that_are_due_for_payment_showed_up_in_ical

**Comment by floehopper** [comment]
I've attempted to add support for overdue bills in 0905f19156370580b1acdf712c5318fb6748280e which is in the overdue-bills branch. I suggest we wait and see whether the fix for #4 works on Monday before putting this in master and deploying it. Cheers, JM.

**Comment by floehopper** [comment]
There's now another commit in this branch, because I broke the build - c90dc7137d9904fefedefe3c43ce301a2970be03.

**Comment by floehopper** [comment]
I'm going to deploy this now and see if it works on Monday before marking it as closed.
